### ISSUE TITLE
Code mistake, unknown token variable

### ISSUE THREAD

**Issue by mcannesson** [lpg2709/clickup_api#16]
Hello,
It seems there is a mistake in some methods, you get the token from this but you set it into an unknown variable "token".

Looks of in List
![image](https://github.com/lpg2709/clickup_api/assets/42031615/89fdf493-75d3-4a18-b140-4eda4684f946)

But not well in Teams (and maybe in others methods)
![image](https://github.com/lpg2709/clickup_api/assets/42031615/7bc81b77-62e1-43b2-8a9d-c7a52a35e9ec)

Thanks.

Best regards.

**Comment by lpg2709** [comment]
Hi, This seems to be only a LSP alert. The token is inherited from Clickup class, and i only make an internal copy inside every function.

This (LSP mistake) seems heppen because i forgget to put the declaration identifier for the local token variable (🙃) . Because is JS, this problabi not affact the module work unitl i fix.

Gonna be fixed on the next update.

Tks for the feedback.

**Comment by mcannesson** [comment]
Thanks for your reply.
